name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg imagemagick
          npm install

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ZALL_GITHUB_TOKEN }}
        run: |
          git config --global user.name "rizalzall"
          git config --global user.email "payahhawok@gmail.com"
          
          # Add all changes, excluding those ignored in .gitignore
          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push https://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@github.com/rizalzall/delta-neww.git master
